trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'norberta200506acr.azurecr.io/norberta200506:0.1'

paths:
    include:
    - NorBERTa/docker/norberta-dockerfile


steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: NorBERTa/docker/norberta-dockerfile