trigger:
  branches:
    include:
    - master

  paths:
    include:
    - NorBERTa/docker/norberta-dockerfile

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'norberta200506acr.azurecr.io/norberta200506'
  DOCKER_BUILDKIT: 1

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: NorBERTa/docker/norberta-dockerfile
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
    # the makefile depends on a file in the parent dir, so the build context must be cd .. :
    buildContext: $(Build.Repository.LocalPath)/NorBERTa
    # buildContext: $(System.DefaultWorkingDirectory)
