apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    service: norberta200506
  name: norberta200506
  namespace: norberta200506ns
spec:
  ports:
  - name: "22"
    port: 22
    targetPort: 22
  selector:
    service: norberta200506
status:
  loadBalancer: {}
