version: '2.2'
services:
  elasticsearch:
    image: custom/elasticsearch:latest
    container_name: elasticsearch-ctr
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - common_net

  kibana:
    image: custom/kibana:latest
    container_name: kibana-ctr
    hostname: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - common_net
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  common_net:
