version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: es-ctr
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.license.self_generated.type=trial
# https://www.elastic.co/guide/en/app-search/current/security-and-users.html#app-search-self-managed-security-and-user-management-within-elasticsearch      
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.authc.realms.native.native1.order=0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: ['stack']

  enterprisesearch:
    image: docker.elastic.co/enterprise-search/enterprise-search:$ELASTIC_VERSION
    container_name: enterprise-ctr
    environment:
    - "ent_search.auth.source=standard"
    - "elasticsearch.username=elastic"
    - "elasticsearch.password=$ELASTIC_PASSWORD"
    - "elasticsearch.host=http://elasticsearch:9200"
    - "allow_es_settings_modification=true"
    - "secret_management.encryption_keys=[XYZ]"
    - "ENT_SEARCH_DEFAULT_PASSWORD=$ELASTIC_PASSWORD"
# Configure enterprise search to use elasticsearch internal native realm, and allow kibana to connect to it too
    - "ent_search.auth.source=elasticsearch-native"
    ports: ['3002:3002']
    networks: ['stack']
    links: ['elasticsearch']
    depends_on: ['elasticsearch']

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: kibana-ctr
    hostname: kibana
    environment:
    - "ELASTICSEARCH_USERNAME=elastic"
    - "ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports: ['5601:5601']
    networks: ['stack']
    depends_on: ['enterprisesearch']

volumes:
  esdata:
    driver: local

networks:
  stack: {}