version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: quepid-es-ctr
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      #- xpack.security.authc.realms.native.native1.order=0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-quepid:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro     
    ports: ['9200:9200']
    networks: ['quepid']

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: quepid-kibana-ctr
    environment:
    - "ELASTICSEARCH_USERNAME=elastic"
    - "ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD"
    volumes:
      - ./kibana/config:/usr/share/kibana/config:ro
    ports: ['5601:5601']
    networks: ['quepid']
    depends_on: ['elasticsearch']

  mysql:
    container_name: quepid_prod_db
    image: mysql:5.6.37
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - mysql-data-quepid:/var/lib/mysql
    networks: ['quepid']

  redis:
    container_name: quepid_prod_redis
    image: redis:6.0.5
    ports:
      - 6379:6379
    networks: ['quepid']

  app:
    container_name: quepid_prod_app
    image: o19s/quepid:latest
    environment:
      - PORT=3000
      - RACK_ENV=production
      - RAILS_ENV=production
      - DATABASE_URL=mysql2://root:$MYSQL_PASSWORD@mysql:3306/quepid
      - REDIS_URL=redis://redis:6379/1
      - FORCE_SSL=false
      - MAX_THREADS=2
      - WEB_CONCURRENCY=2
      - SECRET_KEY_BASE=some_value_needed_here
      - TC_URL=
      - PRIVACY_URL=
      - COOKIES_URL=
      - EMAIL_MARKETING_MODE=false
      - DEFAULT_QUEPID_SCORER=AP@10
      - SIGNUP_ENABLED=true
      - COMMUNAL_SCORERS_ONLY=false
    command: "foreman s -f Procfile"
    ports:
      - 3000:3000 # Map to port 3000 for outside users.
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    networks: ['quepid']

volumes:
  esdata-quepid:
    driver: local
  mysql-data-quepid:
    driver: local

networks:
  quepid: {}